var didScroll;var lastScrollTop=navbarHeight=0;var paged=1;var delta=5;var winHeight=$(window).height();var target="mobile";if(window.matchMedia("(min-width: 1024px)").matches){target="desktop";}
$(document).click(function(e){var targetbox=$('.open');if(!targetbox.is(e.target)&&targetbox.has(e.target).length===0){targetbox.removeClass('open');$('.mainNav__list').css('height','0');}});$(document).ready(function(){checkAceptaCookies();setButtons();setPortada();readCustomUrl();readLogOut();setPopUps();initVIP();ajusteVideo();initOutbrain();ajusteAltoWrapperA();});$(window).resize(function(){ajusteVideo();ajusteAltoWrapperA();});function initOutbrain(){if(target=='desktop'){$('.OUTBRAIN:not(.'+target+')').remove();(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="//widgets.outbrain.com/outbrain.js";fjs.parentNode.insertBefore(js,fjs);}(document,'script','outbrainresp'));}}
function setButtons(){$('.triggerMenu').click(function(){$(this).toggleClass('open');$('.mainNav').toggleClass('open');$('.triggerVip, .navloginVip, .busqueda__trigger, .buscar').removeClass('open');if($(this).hasClass("open")){var ulcats=$('.mainNav__list li').length;alto=((ulcats/2)*60)+60+148;}
$('.mainNav__list').css('height',alto+'px');});$('.triggerVip').click(function(){$(this).toggleClass('open');$('.navloginVip').toggleClass('open');$('.triggerMenu, .mainNav, .busqueda__trigger, .buscar').removeClass('open');$('.mainNav__list').css('height','0');});$(".busqueda__trigger").click(function(){$(".buscar").toggleClass("open");$('.triggerMenu, .mainNav, .triggerVip, .navloginVip').removeClass('open');$('.mainNav__list').css('height','0');});}
function setPortada(){var bgcolor=$('body').css('background-color');var catimportante=$('.wrapperDestacados span.stiker--categoria');var single=$('.single');if(catimportante.length){$('body').addClass('home');}
if(bgcolor!='rgba(0, 0, 0, 0)'&&!single.length){$('ul.wrapperZoneA, ul.wrapperZoneB').addClass('home--skin');$('body').addClass('home');}}
function ajusteVideo(){if($('body').hasClass("single")){var iframeYT=$('iframe[src*="youtube"]');if(iframeYT.length){iframeYT.parent().addClass('videoWrapper');}}}
function moverMegaATF(mega_ATF){var amplioYhome=$('body.single-analisis, body.single-entrevistas, body.home, body.category, body.author, body.tag');if(amplioYhome.length){if(window.matchMedia("(max-width: 1024px)").matches){var megapabajo=$('#'+mega_ATF).parent().detach();if($('body').hasClass("home")||$('body').hasClass("importante")){$('div.wrapperDestacados').append(megapabajo);}else if($('body').hasClass("author")){$('div.cardAuthor.wrapper').after(megapabajo);}else if($('body').hasClass("tag")||($('body').hasClass("category")&&!$('body').hasClass("importante"))){$('h1').after(megapabajo);}else{$('div.headlineSingle__lead').after(megapabajo);}}}}
function ajusteHome(banner){var wrapperZoneA=$('.wrapperZoneA');if(wrapperZoneA.length){if(banner){ajusteAltoWrapperA();}}}
function ajusteAltoWrapperA(){var wrapperZoneA=$('.wrapperZoneA');var altosidebar=0;var alto=altolis=3085;$('.width--sm--sideBar').each(function(index){altosidebar+=$(this).height();});altosidebar+=150;if(altosidebar>altolis){alto=altosidebar;}
if(window.matchMedia("(min-width: 1024px)").matches){if($('body').hasClass('skin')){wrapperZoneA.attr('style','');}else{wrapperZoneA.css('height',alto);}}else{wrapperZoneA.attr('style','');}}
function loadAjaxMasArticulos(){paged+=1;datos={paged:paged,action:'ajax_masarticulos',norepetir:$('#norepetir').val(),cat:$('#cat').val(),post_types:$('#portada_post_types').val(),meta_key:$('#meta_key').val(),meta_compare:$('#meta_compare').val()};$('body').addClass('cargandomas');$.ajax({type:"POST",url:document.location.origin+'/wp-admin/admin-ajax.php',data:datos,dataType:"html",success:function(data){if(data){$("#excesivo").before(data);var stateObj={page:paged};history.pushState(stateObj,'/page/'+paged,'/page/'+paged);trackInGA('ajax_masarticulos','home',window.location.href);}
$('body').removeClass('cargandomas');}});}
function loadAjaxMasPosts(action){paged+=1;$('body').addClass('cargandomas');var category=$('.activa').data('slug');if(category){category="&category="+category;}else{category="";}
$.ajax({type:"POST",url:document.location.origin+'/wp-admin/admin-ajax.php',data:"action="+action+"&paged="+paged+category,dataType:"html",success:function(data){if(data){$("#excesivo").before(data);trackInGA(action,'hub',window.location.href);}else{$("#excesivo").remove();}
$('body').removeClass('cargandomas');}});}
function checkAceptaCookies(){var aceptaCookies=store("aceptaCookies");if(!aceptaCookies){var cukis=$('.cookies');cukis.addClass('mostrar').find('.closeCookies').click(function(){cukis.removeClass('mostrar');});}
store("aceptaCookies",1);}
function getParam(param){var url=window.location.href.slice(window.location.href.indexOf('?')+ 1).split('&');for(var i=0;i<url.length;i++){var params=url[i].split("=");if(params[0]==param)
return params[1];}
return false;}
function putMessage(txt){$("header").append("<div class='mensaje'>"+txt+"</div>");setTimeout(function(){$('.mensaje').slideUp('slow');},3000);}
function readLogOut(){if(getParam('sesion')=='cerrada'){putMessage("Has cerrado sesión correctamente");}else if(getParam('sesion')=='abierta'){putMessage("Has iniciado sesión correctamente");}else if(getParam('userpass')=='incorrecto'){putMessage("Usuario o contraseña incorrectos");}else if(getParam('password')=='reset'){putMessage("Acabamos de enviarte el link para restaurar tu contraseña. Por favor, revisa tu email");}else if(getParam('password')=='resetok'){putMessage("Tu contraseña ha sido restaurada. Por favor, inicia sesión");}}
function setPopUps(){initPopUps('triggerPopup','popup-noPublicidad');initPopUps('loginPopup','popup--register');}
function initPopUps(cclick,cshow){$('.'+cclick).click(function(){$('.'+cshow).fadeIn();$(document).bind('keydown',function(e){if(e.which==27){cerrarPopUps(cshow,cclick);}});$('.btn--close').click(function(){cerrarPopUps(cshow,cclick);});if(cclick=='loginPopup'){bodyCargando("loginnormal");$('.recordar').click(function(event){event.preventDefault();$('#recordarpass').slideToggle();$('#loginnormal').slideToggle();bodyCargando("recordarpass");});}else{trackInGA('ocultar publicidad','abrir aviso');}});}
function cerrarPopUps(cshow,cclick){$('.'+cshow).fadeOut();if(cclick=='triggerPopup'){trackInGA('ocultar publicidad','cerrar');}}
function bodyCargando(formulario){var $form=$('#'+formulario);$form.submit(function(event){event.preventDefault();$('body').addClass('cargando');$form.get(0).submit();});}
$(window).scroll(function(event){didScroll=true;});var barraup=setInterval(function(){if(didScroll){hasScrolled();didScroll=false;}},245);function hasScrolled(){var st=$(this).scrollTop();var resta=Math.abs(lastScrollTop- st);if(Math.abs(lastScrollTop- st)<=delta)
return;var clase='nav-up';var elemento='#hs';var body=$("body");var catpat=$(".patrocinada");var banner=$(".banner");if(body.hasClass("single")&&!body.hasClass("single-patrocinado")&&banner.length&&!catpat.length){clase='slidedown';elemento=".avisoheader";}
if(st>lastScrollTop&&st>55){$(elemento).addClass(clase);}else{if(st+ winHeight<$(document).height()){$(elemento).removeClass(clase);}}
lastScrollTop=st;}
function trackInGA(category,action){ga('send','event',category,action,window.location.href);}
function abreCompartir(event,donde,postid){event.preventDefault();var curpost=$('.post-'+postid);var url=curpost.find('.longurl').val();var title=curpost.find(' .headlineSingle__title').text();var shorturl=curpost.find('.shorturl');if(shorturl.length){if(shorturl.val()){url=shorturl.val();}}
if(donde=='tw'){url="https://twitter.com/intent/tweet?url="+url+"&amp;text="+title+"&utm_source=self&utm_medium=singlenav&utm_campaign=botontw";}else if(donde=='fb'){url="https://www.facebook.com/sharer/sharer.php?u="+url+"&utm_source=self&utm_medium=singlenav&utm_campaign=botonfb";}else{url="mailto:?subject="+encodeURI(title)+"&body="+encodeURI(title+"\nMás info aquí: "+ url);}
window.open(url,'myWindow','status = 1, height = 550, width = 550, resizable = 0');trackInGA("compartir en single",donde,window.location.href);}
function getShortUrl(){var user_id=$('#user_id').val();var url=window.location.href+'?tag='+user_id+'&exp='+(((user_id*2)+5)*3);var token='fd0c86945ee6b8348cc327ed6aa182f3f2d96c15';$.get("https://api-ssl.bitly.com/v3/shorten",{access_token:token,longUrl:url,format:'txt'}).done(function(data){var amplio=$('body.single-analisis, body.single-entrevistas');var clase='';if(amplio.length){clase='M20--md';}
$(".compartir").append('<div class="cs '+clase+'"><input type="text" class="shorturl" name="shorturl" value="'+data+'" /></div>');showControlBar();});}
function setFontSize(value){if(value>=16&&value<=20){var georgia="";var historia=$(".historia");if(historia.hasClass("georgia")){georgia=" georgia";}
historia.removeClass(function(index,className){return(className.match(/(^|\s)tamanio\S+/g)||[]).join(' ');}).addClass('tamanio'+value+georgia);var li=$('.notas-finales li');if(li.length){li.css('font-size',value+"px");}
$('#fontsize').val(value);store("fontsize",value);}}
function showControlBar(){var clase='floatRight';var amplio=$('body.single-analisis, body.single-entrevistas, body.single-especiales');var target='figure.articleHead';if(amplio.length){target='.botonera';clase='';}
var figcaption=$('figure.articleHead figcaption');if(figcaption.length){figcaption.addClass('hayvc');}
var minhtml='<div class="vc '+clase+'"> <div class="medalla"></div><div class="changefont"></div><div class="changesize"> <div class="small"></div><input id="fontsize" max="20" min="16" name="fontsize" type="range" value="18"> <div class="big"></div></div><div class="reset"></div></div></div>';$(target).append(minhtml).slideDown();initControlBar();}
function initVIP(){var isVip=$("#supertop");if(isVip.length){if(isVip.val()){$('body').addClass('esvip');getShortUrl();}}}
function initControlBar(){var fontsize=store("fontsize");var fontfamily=store("fontfamily");if(fontsize){setFontSize(fontsize);}
if(fontfamily){$('.historia').addClass('georgia');$('.changefont').addClass('georgia');}
$('#fontsize').change(function(){setFontSize(this.value);});$('.small').click(function(){setFontSize(parseInt($('#fontsize').val())-1);});$('.big').click(function(){setFontSize(parseInt($('#fontsize').val())+1);});$('.changefont').click(function(){var his=$('.historia');if(his.hasClass("georgia")){his.removeClass('georgia');$(this).removeClass('georgia');store("fontfamily",'');}else{his.addClass('georgia');$(this).addClass('georgia');store("fontfamily",'georgia');}});$('.reset').click(function(){var dfontsize=18;setFontSize(dfontsize);$('#fontsize').val(dfontsize);$('.historia').removeClass(function(index,className){return(className.match(/(^|\s)tamanio\S+/g)||[]).join(' ');}).removeClass('georgia');$('.changefont').removeClass('georgia');store("fontfamily",'');});}
function readCustomUrl(){$.ajax({type:"POST",url:'/wp-admin/admin-ajax.php',data:"action=ajax_customurl&tag="+getParam('tag')+"&exp="+getParam('exp'),dataType:"html",success:function(data){var target=false;var contenidos=$(".headlineSingle");if(contenidos.length){target=contenidos;}
var clase="";var especial=$("#indice");if(especial.length){target=especial;clase="center";}
if(target){target.before(data);$('.vipusershare').addClass(clase);setTimeout(function(){$('.flip-container').addClass("open");},50);}}});}